title: TECKS
description: In this site we have attempted to bring together in one place the scientific research on learning and teaching so that teachers, teacher educators, and teaching researchers have a well organised and accessible source of scientific information regarding what works and what doesn’t work in the classroom.


remote_theme: pdmosses/just-the-docs

url: https://www.tecks.co.nz

exclude: ['data-processing', 'steps.md']